// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SzereloMuhely.Data;

#nullable disable

namespace SzereloMuhely.Migrations
{
    [DbContext(typeof(ServiceContext))]
    [Migration("20260416120805_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SzereloMuhely.Models.Material", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("WorkProcessID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WorkProcessID");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("SzereloMuhely.Models.Part", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("WorkProcessID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WorkProcessID");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("SzereloMuhely.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SzereloMuhely.Models.Vehicle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkSheetID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WorkSheetID")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SzereloMuhely.Models.WorkProcess", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkSheetID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WorkSheetID");

                    b.ToTable("WorkProcesses");
                });

            modelBuilder.Entity("SzereloMuhely.Models.WorkSheet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MechanicID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MechanicID");

                    b.ToTable("WorkSheets");
                });

            modelBuilder.Entity("SzereloMuhely.Models.Mechanic", b =>
                {
                    b.HasBaseType("SzereloMuhely.Models.User");

                    b.HasDiscriminator().HasValue("Mechanic");
                });

            modelBuilder.Entity("SzereloMuhely.Models.WorkRecorder", b =>
                {
                    b.HasBaseType("SzereloMuhely.Models.User");

                    b.HasDiscriminator().HasValue("WorkRecorder");
                });

            modelBuilder.Entity("SzereloMuhely.Models.Material", b =>
                {
                    b.HasOne("SzereloMuhely.Models.WorkProcess", "WorkProcess")
                        .WithMany("Materials")
                        .HasForeignKey("WorkProcessID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkProcess");
                });

            modelBuilder.Entity("SzereloMuhely.Models.Part", b =>
                {
                    b.HasOne("SzereloMuhely.Models.WorkProcess", "WorkProcess")
                        .WithMany("Parts")
                        .HasForeignKey("WorkProcessID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkProcess");
                });

            modelBuilder.Entity("SzereloMuhely.Models.Vehicle", b =>
                {
                    b.HasOne("SzereloMuhely.Models.WorkSheet", "WorkSheet")
                        .WithOne("Vehicle")
                        .HasForeignKey("SzereloMuhely.Models.Vehicle", "WorkSheetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkSheet");
                });

            modelBuilder.Entity("SzereloMuhely.Models.WorkProcess", b =>
                {
                    b.HasOne("SzereloMuhely.Models.WorkSheet", "WorkSheet")
                        .WithMany("WorkProcesses")
                        .HasForeignKey("WorkSheetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkSheet");
                });

            modelBuilder.Entity("SzereloMuhely.Models.WorkSheet", b =>
                {
                    b.HasOne("SzereloMuhely.Models.Mechanic", null)
                        .WithMany("WorkSheets")
                        .HasForeignKey("MechanicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SzereloMuhely.Models.WorkProcess", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Parts");
                });

            modelBuilder.Entity("SzereloMuhely.Models.WorkSheet", b =>
                {
                    b.Navigation("Vehicle")
                        .IsRequired();

                    b.Navigation("WorkProcesses");
                });

            modelBuilder.Entity("SzereloMuhely.Models.Mechanic", b =>
                {
                    b.Navigation("WorkSheets");
                });
#pragma warning restore 612, 618
        }
    }
}
