// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SzereloMuhely.Data;

#nullable disable

namespace SzereloMuhely.Migrations
{
    [DbContext(typeof(ServiceContext))]
    [Migration("20260428232310_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SzereloMuhely.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SzereloMuhely.Models.Vehicle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkSheetID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WorkSheetID")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SzereloMuhely.Models.WorkItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("WorkItems");

                    b.HasDiscriminator<string>("Discriminator").HasValue("WorkItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SzereloMuhely.Models.WorkSheet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MechanicID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecruiterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("WorkSheets");
                });

            modelBuilder.Entity("SzereloMuhely.Models.Material", b =>
                {
                    b.HasBaseType("SzereloMuhely.Models.WorkItem");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("WorkProcessID")
                        .HasColumnType("int");

                    b.HasIndex("WorkProcessID");

                    b.ToTable("WorkItems", t =>
                        {
                            t.Property("Quantity")
                                .HasColumnName("Material_Quantity");

                            t.Property("WorkProcessID")
                                .HasColumnName("Material_WorkProcessID");
                        });

                    b.HasDiscriminator().HasValue("Material");
                });

            modelBuilder.Entity("SzereloMuhely.Models.Part", b =>
                {
                    b.HasBaseType("SzereloMuhely.Models.WorkItem");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("WorkProcessID")
                        .HasColumnType("int");

                    b.HasIndex("WorkProcessID");

                    b.HasDiscriminator().HasValue("Part");
                });

            modelBuilder.Entity("SzereloMuhely.Models.WorkProcess", b =>
                {
                    b.HasBaseType("SzereloMuhely.Models.WorkItem");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("WorkSheetID")
                        .HasColumnType("int");

                    b.HasIndex("WorkSheetID");

                    b.HasDiscriminator().HasValue("WorkProcess");
                });

            modelBuilder.Entity("SzereloMuhely.Models.Vehicle", b =>
                {
                    b.HasOne("SzereloMuhely.Models.WorkSheet", "WorkSheet")
                        .WithOne("Vehicle")
                        .HasForeignKey("SzereloMuhely.Models.Vehicle", "WorkSheetID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkSheet");
                });

            modelBuilder.Entity("SzereloMuhely.Models.Material", b =>
                {
                    b.HasOne("SzereloMuhely.Models.WorkProcess", "WorkProcess")
                        .WithMany("Materials")
                        .HasForeignKey("WorkProcessID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkProcess");
                });

            modelBuilder.Entity("SzereloMuhely.Models.Part", b =>
                {
                    b.HasOne("SzereloMuhely.Models.WorkProcess", "WorkProcess")
                        .WithMany("Parts")
                        .HasForeignKey("WorkProcessID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkProcess");
                });

            modelBuilder.Entity("SzereloMuhely.Models.WorkProcess", b =>
                {
                    b.HasOne("SzereloMuhely.Models.WorkSheet", "WorkSheet")
                        .WithMany("WorkProcesses")
                        .HasForeignKey("WorkSheetID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkSheet");
                });

            modelBuilder.Entity("SzereloMuhely.Models.WorkSheet", b =>
                {
                    b.Navigation("Vehicle")
                        .IsRequired();

                    b.Navigation("WorkProcesses");
                });

            modelBuilder.Entity("SzereloMuhely.Models.WorkProcess", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
